function Ex06() {
  return (
    <div className='h-[200px] w-[500px] overflow-y-scroll border-2 border-black p-5 m-5'>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus, eos vitae. Tempore vel error quidem ipsa nobis voluptas quae perferendis dolorem, cumque molestias minima itaque facere quod ipsam id voluptatibus.
      Tenetur accusantium harum adipisci, provident alias, veniam nostrum aperiam fuga beatae a reprehenderit dicta recusandae libero iste praesentium distinctio eveniet quo quae necessitatibus. Quia, cupiditate itaque? Dolorem blanditiis esse quas?
      Molestiae accusamus soluta adipisci natus beatae quos ullam voluptas! Numquam velit, accusantium quis at nam rerum vel esse, libero laboriosam cum consequuntur eaque vero doloribus modi temporibus id soluta cumque?
      Aut facere ex eos voluptates maxime consectetur soluta optio porro, maiores ipsum? Porro, voluptates quod soluta, earum facere et aspernatur nam tenetur, totam pariatur odit delectus tempore repudiandae qui possimus.
      Eius similique illum id velit saepe culpa laboriosam assumenda esse nihil reiciendis commodi obcaecati accusantium suscipit, facere aperiam voluptatum repudiandae quidem architecto neque expedita deserunt voluptas totam aliquid excepturi. Nihil!
      Qui vero voluptatibus perferendis a, necessitatibus corrupti eum praesentium molestias eligendi quis accusantium dolores culpa facilis fuga quo iusto placeat eaque aspernatur! Placeat expedita aliquid perspiciatis odio sint nobis! Velit.
      Deserunt tenetur perspiciatis sequi harum ratione repellendus aut a iste error, praesentium optio molestiae blanditiis maiores enim placeat ipsa consequatur sint quos nesciunt natus magni vero. Id asperiores quis porro.
      Suscipit eveniet voluptatum sequi consequatur iure eaque facilis nisi dolor porro obcaecati sed, dignissimos minima adipisci libero rem dolorum exercitationem vel illum ducimus nihil? Ullam asperiores fuga incidunt non eveniet?
      Obcaecati aut, nulla officia error incidunt, libero, voluptatibus in expedita atque eligendi magni ipsam? Repellendus, nulla quod, nisi magni soluta obcaecati beatae dolores expedita ipsa pariatur sit provident! Asperiores, est?
      Fugit tenetur accusamus architecto adipisci in beatae deleniti reiciendis, cupiditate ad! Laudantium rem aliquid amet, vitae pariatur eveniet dolore enim corrupti alias sint voluptate a tenetur beatae perspiciatis odit nihil!
      Dolores, blanditiis molestias. Tenetur rerum atque nulla inventore ipsum commodi minus itaque ipsam architecto distinctio voluptate odit, debitis quos temporibus aperiam ut eaque quis iste. Nobis aliquid beatae cumque dolorem!
      Ab quam ullam provident minima, facere fuga, sit cumque omnis odit mollitia, eum earum molestiae consequuntur minus et asperiores doloribus eos amet voluptatibus blanditiis eaque officiis aliquam! Sint, magnam saepe!
      Id tenetur, necessitatibus quibusdam laborum cupiditate vitae ad facilis itaque sint voluptas consequuntur aut eaque illum inventore accusantium, tempora dicta blanditiis. Soluta odio magnam totam aliquam eveniet provident nisi quis.
      Maiores qui, explicabo illum dolor sunt fuga rerum facilis eveniet! Quia fuga libero reiciendis ducimus obcaecati ex magni officiis aliquid atque mollitia. Quo libero nostrum iste neque consectetur excepturi distinctio?
      Magni, officiis veniam! Id culpa ex ducimus magnam aliquid animi ratione excepturi porro molestiae quas amet ipsa qui, odio sed aliquam ullam. Quaerat dolores dolor culpa voluptates tempora! Distinctio, quisquam.
      Laboriosam vitae quo quos alias veritatis delectus enim vero tempore aliquid officiis ab nostrum deleniti rerum ipsam commodi officia dolorum nisi fuga similique, neque impedit! Soluta aperiam rem inventore ea.
      Alias voluptas hic sequi deleniti magnam excepturi. Atque dolores suscipit porro quas? Laborum sunt vitae eveniet! Vero numquam voluptate dignissimos possimus, blanditiis quasi minima quo praesentium, harum laudantium distinctio vitae!
      Saepe non reiciendis obcaecati, exercitationem unde provident, distinctio inventore aperiam pariatur explicabo culpa in aliquid optio a, quis quos vel nobis? Omnis sequi totam consequuntur, dolor harum sint quam nihil.
      Excepturi, impedit eveniet asperiores esse deleniti ratione veniam in id, accusamus quasi sunt, molestias sit. Molestias harum illo sunt debitis, unde temporibus modi facilis possimus, ratione commodi dolor amet? Inventore.
      Saepe ex, cumque, cupiditate, ab provident numquam eligendi culpa vel inventore voluptate reprehenderit odio soluta quod dignissimos nisi. Unde, expedita! Recusandae odit a quos ducimus quasi ut architecto sit aliquid?
      Distinctio qui quibusdam natus perferendis dolores adipisci quo nam repudiandae ad. Tempore soluta facilis cumque id quos voluptas temporibus quam dolore, quaerat doloremque obcaecati, porro dolorum aspernatur! Ipsam, recusandae maiores?
      Natus repudiandae dolorem unde sint, consequatur debitis maxime blanditiis mollitia eveniet ipsum. Ipsa repellendus magnam perferendis nulla fuga explicabo placeat voluptatibus tempore porro provident, hic soluta laboriosam recusandae nisi aut!
      Nostrum reiciendis necessitatibus, sequi suscipit sed similique laudantium alias dolorem voluptatibus quo excepturi perspiciatis, qui cupiditate magnam pariatur aliquam quos? Ipsum ducimus aut tempore illo qui. Possimus suscipit nesciunt vel?
      Architecto debitis quidem possimus beatae, itaque eaque accusamus? Vel eligendi facilis, placeat dolor commodi obcaecati magni quos perspiciatis voluptatem ratione. Tenetur, vero doloribus repudiandae eius debitis tempore quisquam voluptate itaque.
      Ipsa ipsum enim asperiores, repellendus explicabo ut officia iusto laudantium molestiae omnis fuga eveniet aliquam. Sapiente cupiditate consectetur vero facere. Accusamus laudantium laboriosam ratione. Veritatis officiis aut tempore consequuntur! Mollitia?
      Corporis qui optio deleniti ab iusto, commodi vitae officiis amet aut aliquid exercitationem suscipit aperiam necessitatibus pariatur illo culpa facere? Rerum velit nesciunt quidem? Quis ad optio fuga provident aliquam.
      Provident dolorum repudiandae porro voluptatum eveniet laudantium excepturi et perferendis cum distinctio nulla, ut quibusdam quisquam maiores deleniti minus numquam? Voluptates temporibus facere molestiae ad, ex fugiat non facilis minima.
      Facilis inventore illo aperiam at incidunt necessitatibus esse quibusdam nemo aliquam asperiores facere quod praesentium, porro ipsam soluta vel veritatis. Quisquam adipisci nulla laborum ea nesciunt, assumenda similique a illum?
      Ipsa, provident nobis amet odit, exercitationem ipsum incidunt, molestiae recusandae animi minus quos placeat expedita nihil obcaecati in saepe nesciunt? Voluptate aperiam quod quia, consequatur veritatis cumque voluptates quae itaque.
      Dolorem mollitia reiciendis deleniti minus quisquam eaque similique tenetur natus asperiores vitae id magnam voluptatem aperiam vero sunt, quibusdam dolore obcaecati commodi. Officiis minus nobis ipsa repudiandae optio, minima dignissimos!
      Quas repudiandae necessitatibus cum. Autem, voluptatum a animi, ut fuga dolore necessitatibus magnam nam hic nulla mollitia velit cupiditate magni esse harum. Nesciunt ea commodi, aperiam excepturi dolorem sunt veniam.
      Nisi beatae sed ducimus quasi temporibus deleniti, consequatur molestias, facere animi debitis saepe mollitia accusamus minima, expedita distinctio neque dolor. Adipisci praesentium pariatur doloribus animi dolore soluta ut repellendus dolores?
      Iusto quibusdam magnam possimus blanditiis nulla exercitationem voluptates accusamus quasi consequatur, nisi eveniet dolores commodi quod! Explicabo adipisci ducimus vel, eum assumenda et fugit deleniti! Maiores, sed. Dicta, voluptatum exercitationem?
      Alias mollitia nobis molestiae eaque corporis odit quod commodi qui? Error assumenda quas hic dolorem doloribus perferendis ex laboriosam exercitationem est deleniti, tenetur illum provident minima totam odit voluptatem! Tempora.
      Iure magni repudiandae quia dolor quisquam repellat ut cumque autem alias natus modi, harum sed officiis eius molestiae. Commodi culpa optio omnis perspiciatis assumenda excepturi rerum quas, eveniet doloribus. Quae.
      Sit, praesentium quos voluptatem ducimus quia deserunt quaerat labore, fugit odio sint aliquam consequuntur, voluptatum sequi hic quae qui suscipit accusantium magni impedit consequatur cupiditate sapiente earum iure minima? Explicabo?
      Eum provident expedita dolores autem illo fugit quas. Tempora perspiciatis accusamus, optio sunt quasi sequi libero facilis neque aperiam aliquid sint omnis animi dolore iusto consequuntur. Nisi distinctio ab dolorem.
      Expedita explicabo consequuntur repellat pariatur nemo obcaecati molestiae sint odio nihil, cumque velit voluptatem, vero voluptatibus voluptas natus ipsum vitae ullam dolor enim quis iste maiores dolorem. Perspiciatis, porro tempore?
      Dolor pariatur nostrum labore voluptate tempore quos voluptatibus, temporibus deserunt, sapiente dolores sed iure officiis illum dignissimos enim itaque facere autem numquam magni vero obcaecati. Temporibus incidunt pariatur deleniti sequi.
      Nemo, voluptates expedita rem neque aspernatur suscipit vero ab. Alias ab repellendus placeat quibusdam cum commodi ullam ipsum, eveniet minus quia laudantium, doloribus sunt ratione minima earum provident officia harum!
      Ea sunt corrupti, nostrum dolores saepe sapiente unde qui quaerat. Quae minus fuga id eos, ex vitae! Fuga ullam soluta eius, consequatur, dicta facere saepe reprehenderit reiciendis numquam, dolores aut.
      Iure totam, hic ea nam repellat, cum praesentium culpa illum labore et numquam voluptatem corrupti, sequi pariatur rem libero eum! Unde officia corporis voluptas dicta sint? Non facere eos laudantium?
      Vel pariatur numquam voluptatum obcaecati alias beatae sapiente! Itaque doloremque ab error consectetur! Ab molestiae sequi, dolorem delectus magni molestias nulla reprehenderit provident cupiditate dolore fuga ex minima velit quis!
      Velit tempora doloribus labore animi in cupiditate quis, laboriosam dolorem dolore perspiciatis minima magnam odit impedit fugiat, voluptatibus soluta aliquam a quod laudantium voluptatem error illo suscipit harum amet. Saepe?
      Praesentium veritatis ad veniam ex facilis fuga excepturi aliquam eligendi delectus alias, nesciunt accusamus eveniet minima consectetur vero harum quod qui eum ipsam nostrum dolorum similique vitae enim! Voluptates, quam!
      Ad voluptatum dicta odio odit, tempore veniam fugiat dolorem ratione eum ullam repudiandae in asperiores, temporibus blanditiis doloremque nesciunt! Iste obcaecati asperiores corporis id quibusdam! Nesciunt soluta quam qui consequuntur?
      Molestias magnam reprehenderit architecto quia ipsam eaque soluta, magni ratione porro maiores ipsum ipsa! Reprehenderit, consequatur maiores. Soluta earum iure, qui ullam iste sapiente minus vel eligendi, delectus ex possimus?
      Adipisci officia, in modi molestiae illo quis officiis saepe minima voluptatem similique optio explicabo itaque porro voluptate commodi doloremque repellat fugiat asperiores cum. Optio consectetur distinctio eligendi sunt, harum magni!
      Eum, ea. Reiciendis doloremque tempore illum mollitia tenetur! Temporibus nisi dolor voluptatibus ratione! Ipsa quasi error corrupti. Natus nam provident maxime quia quaerat suscipit cupiditate, voluptatibus numquam, ipsa voluptates quasi?
      Quidem, ut? Pariatur incidunt labore neque, quae vitae repellat eum magni dolores dolore cumque hic voluptatibus harum sint, quisquam eaque id consequuntur architecto, perferendis non sunt repudiandae doloremque corporis. Laborum.
    </div>
  )
}

export default Ex06
